name: CI Pipeline

on:
  push:
    branches:
      - test-workflow
  pull_request:
    branches:
      - test-workflow

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "20"

  client:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install client dependencies
        working-directory: ./client
        run: npm i

      - name: Build client
        working-directory: ./client
        run: npm run build

  server:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install server dependencies
        working-directory: ./server
        run: npm i

      - name: Build server
        working-directory: ./server
        run: npm run build
